### ISSUE TITLE
Making examples

### ISSUE THREAD

**Issue by joseeloren** [joseeloren/wxWidgets#12]
It will be great if I do a sample for the samples directory on the library. It's a good way to start with a new "widget" when you didn't use it before.

**Comment by sjlamerton** [comment]
Are you planning something different to the existing [webview sample](https://github.com/wxWidgets/wxWidgets/tree/master/samples/webview) here?

**Comment by joseeloren** [comment]
Yes of course @sjlamerton . I think the new API have to have new functionalities (they must to be discussed). For instance, return a value and do something more with it (to show the utility), do something when an event is trigged from JS with webkit_dom_event_target_add_event_listener() (I have to, on community bounding, check the possibilities on MSW and OSX). We need to show how it works with an example.

webkit_dom_event_target_add_event_listener() information: https://webkitgtk.org/reference/webkitdomgtk/2.3.2/WebKitDOMEventTarget.html#webkit-dom-event-target-add-event-listener

**Comment by joseeloren** [comment]
The sample is already changed.
