### ISSUE TITLE
Modeling a new WebView (API design)

### ISSUE THREAD

**Issue by joseeloren** [joseeloren/wxWidgets#2]
In this part, I will create a new class inherited from Webview (maybe) to support old code and new one made with the new version. For example:

wxString Evaluate (wxString script). It evaluates a JS script and returns return value.
wxString RunFunction (wxString function, wxString[] args). Runs a function with the args given.
void SetEvent(wxString event, wxString elementiId). It creates a event for a element in DOM.
void GetElementByID(wxString id). Gets the value of a DOM element.

Note: wxString will be wxObject or a pointer, it is debatable.

**Comment by sjlamerton** [comment]
If your application is successful it would be good to discuss this API more on the wx-dev mailing list to make sure it works well for everyone.

**Comment by joseeloren** [comment]
Of course @sjlamerton . It's just what I was talking with Mariano Reingart this afternoon. All of this, for me, it's just imagination, we need to discuss and concretate the API.

**Comment by joseeloren** [comment]
Is the API clear? I think it is...
