### ISSUE TITLE
Study docs for wxMSW.

### ISSUE THREAD

**Issue by joseeloren** [joseeloren/wxWidgets#4]
Because of under wxMSW it's implemented with IE library, maybe it's a better option switch to other library or see the possibilities. Study it just a little bit, we will do it better on #8

**Comment by sjlamerton** [comment]
In terms of being able to achieve everything during the summer I think we should stick to IE for now. It isn't clear to me if we could embed Edge even if we wanted too (see [here](http://stackoverflow.com/questions/34327862/mshtml-vs-edgehtml)).

**Comment by joseeloren** [comment]
Okay @sjlamerton . We can discuss it deeply later, but if with IE there is a function to have a return value, it's more than enough. I put it opened because we need to know the possibilities and discuss what is better.

**Comment by joseeloren** [comment]
I'm going to move this to first term milestone (June), because we have to plan what to do in next months.

**Comment by joseeloren** [comment]
This is related to #8 , so I think is already done.
