### ISSUE TITLE
Style revision

### ISSUE THREAD

**Issue by joseeloren** [joseeloren/wxWidgets#5]
At the end, I will be great if I check code style and code conventions, if a I missed up some.

**Comment by sjlamerton** [comment]
Just in case you haven't seen it the wxWidgets coding style is available [here](https://www.wxwidgets.org/develop/coding-guidelines/).

**Comment by joseeloren** [comment]
I have seen it (when I did the bug fixing as requirement of my proposal). I put this issue in order to check that everything is okay, you (I mean, the wxWidgets' team) check the code to see if you agree with variables names, and that kind of stuff.

**Comment by joseeloren** [comment]
I tried to follow the style guide, but it could be fantastic if someone, during pull request, could check this.

**Comment by joseeloren** [comment]
I checked my code with style guide and it seems everything is okay.
