### ISSUE TITLE
Implement RunScript with Return Value using Webkit2 in GTK.

### ISSUE THREAD

**Issue by joseeloren** [joseeloren/wxWidgets#6]
To test the power of WebKit2, I will implement a RunScript function with some Return Values, like read a variable value.

Update 1: There is a Webkit2 integration in progress. I will implement new functions to the library using the new characteristics of WebKit2. More info: [wxWidgets#439](https://github.com/wxWidgets/wxWidgets/pull/439)

**Comment by swt2c** [comment]
Just in case you're not aware yet, there's a pull request in progress to add WebKit2 support to wxWidgets: https://github.com/wxWidgets/wxWidgets/pull/439

Hopefully it will be merged soon.

Feel free to base your work on that or use it for reference.

**Comment by joseeloren** [comment]
Thanks you for the info @swt2c , Mariano Reingart also told me that, I missed up concrete this issue. I mean working in parallel with the integration and implement new functionalities available on the library. I will add this to the main entry of this issue.

**Comment by sjlamerton** [comment]
As I mentioned in my email pull request wxWidgets#439 has now been merged so you should be able to build directly on top of it.

**Comment by joseeloren** [comment]
Okay, I was talking about this with Mariano Reingart. It will be interesting on community bounding solve this ticket, starting for GTK: http://trac.wxwidgets.org/ticket/13859 , using the integration of WebKit2 on GTK.

**Comment by joseeloren** [comment]
Now this is working, waiting for improvements (they are in other issues).
